== Java examples

=== Coding styles

* https://www.overops.com/blog/tabs-vs-spaces-how-they-write-java-in-google-twitter-mozilla-and-pied-piper/[Tabs vs Spaces: How They Write Java at Google, Twitter, Mozilla and Pied Piper - OverOps^]

=== VS-Code

==== Project configuration is not up-to-date with pom.xml, requires an update.

* Before
+
[source,json]
..vscode/settings.json
----
{
  "java.configuration.updateBuildConfiguration": "interactive"
}
----

* After
+
[source,json]
..vscode/settings.json
----
{
  "java.configuration.updateBuildConfiguration": "automatic"
}
----

.References
* https://github.com/microsoft/vscode-maven/issues/132[Project configuration is not up-to-date with pom.xml, requires an update. · Issue #132 · microsoft/vscode-maven^] +
  Project configuration is not up-to-date with pom.xml, requires an update. - Google Search


=== Switch versions

==== Ubuntu 18.04 LTS

[source,console]
----
$ sudo update-alternatives --config java
[sudo] password for guest:
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in manual mode
----