version: "3.7"

services:
  app:
    image: fruits-menu:0.0.1-SNAPSHOT
    container_name: fruits-menu
    ports:
    - 8080:8080
    depends_on:
    - postgres
    env_file: .env.docker_compose
    # environment:
    # - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fruits
    # - SPRING_DATASOURCE_USERNAME=compose-postgres
    # - SPRING_DATASOURCE_PASSWORD=compose-postgres
    # - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    restart: always
    image: postgres:14-alpine
    container_name: postgres-db_user1
    ports:
    - 5432:5432
    env_file: .env.postgres
    volumes:
    - type: bind
      source: "./initdb.d"
      target: "/docker-entrypoint-initdb.d"
    - /var/tmp/postgres-db_user1/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d fruits -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
