ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

include::header.adoc[]

== Install and setup

=== Java

==== Ubuntu 18.04 LTS

. Search Java packages
+
[source,console]
----
$ sudo apt search 'openjdk-[0-9]+-jre$'
[sudo] password for guest:
Sorting... Done
Full Text Search... Done
openjdk-11-jre/bionic-updates,bionic-security 11.0.11+9-0ubuntu2~18.04 amd64 [upgradable from: 11.0.6+10-1ubuntu1~18.04.1]
  OpenJDK Java runtime, using Hotspot JIT

openjdk-17-jre/bionic-updates 17+35-1~18.04 amd64
  OpenJDK Java runtime, using Hotspot JIT

openjdk-8-jre/bionic-updates,bionic-security 8u292-b10-0ubuntu1~18.04 amd64
  OpenJDK Java runtime, using Hotspot JIT
----

. Install Java
+
[source,console]
.Install Java 8 on Ubuntu 18.04 LTS
----
sudo apt-get install openjdk-8-jdk
----

. Check which JDK-Versions are available on your system perform:
+
[source,console]
----
$ sudo update-java-alternatives --list
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.8.0-openjdk-amd64       1081       /usr/lib/jvm/java-1.8.0-openjdk-amd64
----

. Make version 8 your default Java:
+
you get something like this:
+
[source,console]
----
$ sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in manual mode
----

. Repeat the previous operation with default Javac:
+
[source,console]
----
$ sudo update-alternatives --config javac
There are 2 choices for the alternative javac (providing /usr/bin/javac).

  Selection    Path                                          Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/javac   1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/javac   1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/bin/javac    1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in manual mode
----

. Check with `java -version` and `javac -version` that version 8 is the default JDK.
you get something like this:
+
[source,console]
----
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
----
+
[source,console]
----
$ javac -version
javac 1.8.0_292
----

===== Install Maven

. Install Maven
+
[source,console]
----
sudo apt-get update
sudo apt install maven
----

. Check installed
+
[source,console]
----
mvn -version
----

.References
* https://www.geofis.org/en/install/install-on-linux/install-openjdk-8-on-ubuntu-trusty/[Install OpenJDK 8 on Ubuntu Trusty - GeoFIS^] +
  apt install openjdk 8 ubuntu alternative - Google Search

==== Ubuntu 20.04 LTS

. Install Java 17 on Ubuntu 20.04 LTS
+
[source,console]
.Install Java 17 on Ubuntu 20.04 LTS
----
$ sudo apt install openjdk-17-jdk
$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.4, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.16.3-microsoft-standard-wsl2", arch: "amd64", family: "unix"
----
+
[source,console]
----
$ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-120.04, mixed mode, sharing)
$ update-java-alternatives --list
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.17.0-openjdk-amd64      1711       /usr/lib/jvm/java-1.17.0-openjdk-amd64
----
+
[WARNING]
.Maven 3.6.3 not working on Ubuntu 20.04 LTS
====
[source,console]
----
$ sudo apt install openjdk-17-jdk
$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.4, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.16.3-microsoft-standard-wsl2", arch: "amd64", family: "unix"
$ mvn spring-boot:build-image
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
----
====

===== Install Maven

. Download public key
+
[source,console]
----
$ wget https://downloads.apache.org/maven/KEYS
...
$ gpg --import KEYS
...
gpg: Total number processed: 75
gpg:               imported: 74
gpg:              unchanged: 1
gpg: no ultimately trusted keys found
$ rm -f KEYS
----

. Download maven
+
[source,console]
----
$ wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.{gz,gz.asc}
...
$ gpg --verify apache-maven-3.8.6-bin.tar.gz.asc apache-maven-3.8.6-bin.tar.gz
gpg: Signature made Tue Jun  7 01:39:26 2022 JST
gpg:                using RSA key 6A814B1F869C2BBEAB7CB7271A2A1C94BDE89688
gpg: Good signature from "Michael Osipov (Java developer) <1983-01-06@gmx.net>" [unknown]
gpg:                 aka "Michael Osipov <michaelo@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6A81 4B1F 869C 2BBE AB7C  B727 1A2A 1C94 BDE8 9688
$ rm -f apache-maven-3.8.6-bin.tar.gz.asc
----

. Extract tar files to a `/opt` Directory
+
[source,console]
----
$ sudo tar zxf apache-maven-3.8.6-bin.tar.gz -C /opt
$ sudo bash -c "(cd /opt && ln -s apache-maven-3.8.6 apache-maven)"
$ ls -ld /opt/apache-maven*
lrwxrwxrwx 1 root root   18 Sep  4 18:41 /opt/apache-maven -> apache-maven-3.8.6
drwxr-xr-x 6 root root 4096 Sep  4 18:38 /opt/apache-maven-3.8.6
----

. Adding to PATH
+
[source,shell]
.~/.bashrc
----
# ...snip

MAVEN_HOME="/opt/apache-maven"
if [ -d ${MAVEN_HOME} ]; then
    export PATH="${MAVEN_HOME}/bin:$PATH"
fi
----

. Reload shell
+
[source,bash]
----
exec $SHELL -l
----

. Check path and version
+
[source,console]
----
$ type mvn
mvn is /opt/apache-maven/bin/mvn
$ mvn -version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven
Java version: 17.0.4, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.16.3-microsoft-standard-wsl2", arch: "amd64", family: "unix
----

=== VS-Code

ctrl + Shift + P

----
>Java: Configure Java Runtime
----

(workspaceでなく)WSL側に設定を加えると次の警告が消える。

> Build path specifies execution environment JavaSE-1.8. There are no JREs installed in the workspace that are strictly compatible with this environment. 

> The compiler compliance specified is 1.8 but a JRE 11 is used

[source,json]
.~/.vscode-server/data/Machine/settings.json
----
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-1.8",
      "path": "/usr/lib/jvm/java-8-openjdk-amd64",
      "default":  true
    },
    {
      "name": "JavaSE-11",
      "path": "/usr/lib/jvm/java-11-openjdk-amd64/"
    },
  ]
----

.References
* https://code.visualstudio.com/docs/java/java-project#_configure-runtime-for-projects[Configure Runtime for Projects | code.visualstudio.com^]

==== Xxx.java is a non-project file, only syntax errors are reported

Try cleaning the Java language server workspace:

. CMD+SHIFT+P (CTRL+SHIFT+P ON WINDOWS) to show command palette
. Choose "Java: Clean the Java language server workspace"
. Restart and Delete

.References
* https://stackoverflow.com/questions/61826895/how-to-avoid-vs-code-warning-myfile-java-is-a-non-project-file-only-syntax[How to avoid VS Code warning: "[MyFile\].java is a non-project file, only syntax errors are reported" - Stack Overflow^]

=== Maven

. Crete Project
+
[source,console]
----
mvn -B archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -D groupId=com.example.myapp -DartifactId=myapp
----

. Move to project folder.
+
[source,console]
----
cd myapp/
----
+
[source,console]
----
myapp$ tree .
.
├── pom.xml
└── src
    ├── main
    │   └── java
    │       └── com
    │           └── example
    │               └── myapp
    │                   └── App.java
    └── test
        └── java
            └── com
                └── example
                    └── myapp
                        └── AppTest.java

11 directories, 3 files
----

. Build

. Run
+
[source,console]
----
myapp$ cd target/classes/
classes$ java com.example.myapp.App
Hello World!
----

==== trouble shooting

==== Java 8 向けにコンパイルする

.Messages
* Build path specifies execution environment J2SE-1.5. There are no JREs installed in the workspace that are strictly compatible with this environment. 
* The compiler compliance specified is 1.5 but a JRE 1.8 is used

[source,xml]
----
  <properties>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>
----

[source,xml]
.Old style
----
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.1</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
----

* https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html[Apache Maven Compiler Plugin – Setting the -source and -target of the Java Compiler | maven.apache.org^]


=== References

// tag::reference[]
* https://qiita.com/KevinFQ/items/e8363ad6123713815e68[よく使うMavenコマンド集 - Qiita^] +
  maven build - Google 検索
// end::reference[]
